[agentx]
ollama_host = "localhost:11434"
ollama_model = "gpt-oss"
ollama_initial_load_timeout_seconds = 120
screen_side = "left"
user_prompt_font_background = "#888888"
agent_response_font_background = "#ffffff"
agent_thinking_font_background = "#eeeeee"